[2022-09-25 22:50:25,654] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: Email_Bestseller_List_To_Users.NonFiction_book_list 2022-09-25T22:50:20.580220+00:00 [queued]>
[2022-09-25 22:50:25,669] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: Email_Bestseller_List_To_Users.NonFiction_book_list 2022-09-25T22:50:20.580220+00:00 [queued]>
[2022-09-25 22:50:25,670] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2022-09-25 22:50:25,670] {taskinstance.py:1069} INFO - Starting attempt 1 of 1
[2022-09-25 22:50:25,670] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2022-09-25 22:50:25,690] {taskinstance.py:1089} INFO - Executing <Task(PythonOperator): NonFiction_book_list> on 2022-09-25T22:50:20.580220+00:00
[2022-09-25 22:50:25,700] {standard_task_runner.py:52} INFO - Started process 198 to run task
[2022-09-25 22:50:25,706] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Email_Bestseller_List_To_Users', 'NonFiction_book_list', '2022-09-25T22:50:20.580220+00:00', '--job-id', '73', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/DAG1.py', '--cfg-path', '/tmp/tmpnf4xwj0g', '--error-file', '/tmp/tmp5s_t_swc']
[2022-09-25 22:50:25,706] {standard_task_runner.py:77} INFO - Job 73: Subtask NonFiction_book_list
[2022-09-25 22:50:25,767] {logging_mixin.py:104} INFO - Running <TaskInstance: Email_Bestseller_List_To_Users.NonFiction_book_list 2022-09-25T22:50:20.580220+00:00 [running]> on host d74d0d8a09f8
[2022-09-25 22:50:25,829] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Email_Bestseller_List_To_Users
AIRFLOW_CTX_TASK_ID=NonFiction_book_list
AIRFLOW_CTX_EXECUTION_DATE=2022-09-25T22:50:20.580220+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-25T22:50:20.580220+00:00
[2022-09-25 22:50:25,830] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/DAG1.py", line 37, in Get_Combined_NonFiction_Book_List
    Combined_NonFiction_List_Details=Combined_NonFiction_List['results']['books']
TypeError: string indices must be integers
[2022-09-25 22:50:25,837] {taskinstance.py:1532} INFO - Marking task as FAILED. dag_id=Email_Bestseller_List_To_Users, task_id=NonFiction_book_list, execution_date=20220925T225020, start_date=20220925T225025, end_date=20220925T225025
[2022-09-25 22:50:25,881] {local_task_job.py:146} INFO - Task exited with return code 1
